import { describe, expect, test } from 'vitest';
// Type-only exports — this block verifies that all type exports exist at compile time.
// If any type is accidentally removed from the barrel, `pnpm typecheck` will catch it.
import type {
  AnnotationOverlayProps,
  Bookmark,
  CharacterInfo,
  CharBox,
  Colour,
  ContainerState,
  DefaultToolbarProps,
  DragDropZoneProps,
  FirstLastPageRenderProps,
  FitState,
  FullscreenRenderProps,
  FullscreenState,
  InteractionMode,
  InteractionModeRenderProps,
  InteractionModeState,
  MarqueeOverlayProps,
  MarqueeRect,
  NamedDestination,
  NavigationState,
  PanelConfig,
  PanelEntry,
  PanelId,
  PDFCanvasProps,
  PDFDocumentViewHandle,
  PDFiumContextValue,
  PDFiumErrorBoundaryProps,
  PDFiumProviderProps,
  PDFiumThemeMode,
  PDFViewerClassNames,
  PDFViewerProps,
  PDFViewerState,
  PrintRenderProps,
  PrintState,
  RenderOptions,
  RotationRenderProps,
  RotationState,
  ScrollMode,
  ScrollModeState,
  SearchHighlightOverlayProps,
  SearchInputProps,
  SearchRenderProps,
  SerialisedAnnotation,
  SerialisedAttachment,
  SerialisedFormWidget,
  SerialisedLink,
  SerialisedPageObject,
  SidebarPanelProps,
  SpreadMode,
  SpreadModeState,
  SpreadRenderProps,
  StructureElement,
  TextLayerProps,
  TextOverlayProps,
  TextSearchResult,
  ToolbarContextValue,
  ToolbarSearchState,
  UseVisiblePagesOptions,
  UseVisiblePagesResult,
  VisiblePage,
  WebLink,
  WorkerPDFiumDocument,
  ZoomAnchor,
  ZoomState,
} from '../../../src/react/index.js';
import * as ReactAPI from '../../../src/react/index.js';

describe('React Public API', () => {
  test('should export expected runtime symbols', () => {
    const exports = Object.keys(ReactAPI).sort();
    expect(exports).toMatchSnapshot();
  });

  // Compile-time assertion: if any type export is accidentally removed from the
  // barrel, this test file will fail `pnpm typecheck` due to unresolvable imports.
  // The types are referenced in a dead-code assertion that TypeScript still checks.
  test('type exports exist at compile time', () => {
    // This function is never called — its sole purpose is to create type references
    // that TypeScript validates at compile time. If any imported type is removed
    // from the barrel, `pnpm typecheck` will report an unresolvable import error.
    function _typeAssertions(
      _a: AnnotationOverlayProps,
      _b: Bookmark,
      _c: CharacterInfo,
      _d: CharBox,
      _e: Colour,
      _f: ContainerState,
      _g: DefaultToolbarProps,
      _h: DragDropZoneProps,
      _i: FirstLastPageRenderProps,
      _j: FitState,
      _k: FullscreenRenderProps,
      _l: FullscreenState,
      _m: InteractionMode,
      _n: InteractionModeRenderProps,
      _o: InteractionModeState,
      _p: MarqueeOverlayProps,
      _q: MarqueeRect,
      _r: NamedDestination,
      _s: NavigationState,
      _si: PanelConfig,
      _sj: PanelEntry,
      _sk: PanelId,
      _t: PDFCanvasProps,
      _u: PDFDocumentViewHandle,
      _v: PDFiumContextValue,
      _w: PDFiumErrorBoundaryProps,
      _x: PDFiumProviderProps,
      _y: PDFiumThemeMode,
      _z: PDFViewerClassNames,
      _aa: PDFViewerProps,
      _ab: PDFViewerState,
      _ac: PrintRenderProps,
      _ad: PrintState,
      _ae: RenderOptions,
      _af: RotationRenderProps,
      _ag: RotationState,
      _ah: ScrollModeState,
      _ahi: ScrollMode,
      _ai: SearchHighlightOverlayProps,
      _aj: SearchInputProps,
      _ak: SearchRenderProps,
      _al: SerialisedAnnotation,
      _am: SerialisedAttachment,
      _an: SerialisedFormWidget,
      _ao: SerialisedLink,
      _ap: SerialisedPageObject,
      _aq: SidebarPanelProps,
      _ar: SpreadMode,
      _as: SpreadModeState,
      _at: SpreadRenderProps,
      _au: StructureElement,
      _av: TextLayerProps,
      _aw: TextOverlayProps,
      _ax: TextSearchResult,
      _ay: ToolbarContextValue,
      _ayi: ToolbarSearchState,
      _ayj: UseVisiblePagesOptions,
      _ayk: UseVisiblePagesResult,
      _ayl: VisiblePage,
      _az: WebLink,
      _ba: WorkerPDFiumDocument,
      _bai: ZoomAnchor,
      _bb: ZoomState,
    ) {
      return [
        _a,
        _b,
        _c,
        _d,
        _e,
        _f,
        _g,
        _h,
        _i,
        _j,
        _k,
        _l,
        _m,
        _n,
        _o,
        _p,
        _q,
        _r,
        _s,
        _si,
        _sj,
        _sk,
        _t,
        _u,
        _v,
        _w,
        _x,
        _y,
        _z,
        _aa,
        _ab,
        _ac,
        _ad,
        _ae,
        _af,
        _ag,
        _ah,
        _ahi,
        _ai,
        _aj,
        _ak,
        _al,
        _am,
        _an,
        _ao,
        _ap,
        _aq,
        _ar,
        _as,
        _at,
        _au,
        _av,
        _aw,
        _ax,
        _ay,
        _ayi,
        _ayj,
        _ayk,
        _ayl,
        _az,
        _ba,
        _bai,
        _bb,
      ];
    }

    // The function exists — that's the assertion. It's never called.
    expect(typeof _typeAssertions).toBe('function');
  });
});
