const BOOKMARK_TREE_INDENT_VAR = 'var(--pdfium-bookmark-indent, 16px)';
const BOOKMARK_TREE_ITEM_HORIZONTAL_PADDING = '8px';
const BOOKMARK_TREE_ITEM_VERTICAL_PADDING = '4px';
const BOOKMARK_TREE_ITEM_PADDING = `${BOOKMARK_TREE_ITEM_VERTICAL_PADDING} ${BOOKMARK_TREE_ITEM_HORIZONTAL_PADDING}`;

const BOOKMARK_TREE_GLYPH_SIZE = 16;
const BOOKMARK_TREE_TRANSITION = 'transform 0.15s ease';

const BOOKMARK_TREE_ITEM_FONT_SIZE = '0.875em';
const BOOKMARK_TREE_PAGE_BADGE_FONT_SIZE = '0.8em';
const BOOKMARK_TREE_FILTER_INPUT_FONT_SIZE = '0.8125em';
const BOOKMARK_TREE_FILTER_COUNT_FONT_SIZE = '0.75em';

const BOOKMARK_TREE_FILTER_INPUT_PADDING = '6px 10px';
const BOOKMARK_TREE_FILTER_COUNT_PADDING = '2px 8px';

const BOOKMARK_TREE_GROUP_PADDING = '4px 0';

const BOOKMARK_TREE_PAGE_BADGE_PADDING_LEFT = 8;

function getBookmarkTreeItemPaddingLeft(depth: number): string {
  return `calc((${BOOKMARK_TREE_INDENT_VAR} * ${depth}) + ${BOOKMARK_TREE_ITEM_HORIZONTAL_PADDING})`;
}

export {
  BOOKMARK_TREE_FILTER_COUNT_FONT_SIZE,
  BOOKMARK_TREE_FILTER_COUNT_PADDING,
  BOOKMARK_TREE_FILTER_INPUT_FONT_SIZE,
  BOOKMARK_TREE_FILTER_INPUT_PADDING,
  BOOKMARK_TREE_GLYPH_SIZE,
  BOOKMARK_TREE_GROUP_PADDING,
  BOOKMARK_TREE_INDENT_VAR,
  BOOKMARK_TREE_ITEM_FONT_SIZE,
  BOOKMARK_TREE_ITEM_HORIZONTAL_PADDING,
  BOOKMARK_TREE_ITEM_PADDING,
  BOOKMARK_TREE_ITEM_VERTICAL_PADDING,
  BOOKMARK_TREE_PAGE_BADGE_FONT_SIZE,
  BOOKMARK_TREE_PAGE_BADGE_PADDING_LEFT,
  BOOKMARK_TREE_TRANSITION,
  getBookmarkTreeItemPaddingLeft,
};
