export type {
  BoxAppearance,
  ScreenLine,
  SelectionMarkupQuad,
  SelectionOverlayAppearance,
  SelectionOverlayProps,
  TextMarkupSelectionKind,
} from './selection-overlay-appearance.types.js';
export {
  BOX_CURSOR_MAP,
  BOX_HANDLES,
  DEFAULT_BOUNDS_BORDER_COLOUR,
  DEFAULT_DISABLED_BOUNDS_BACKGROUND,
  DEFAULT_DISABLED_BOUNDS_BORDER_COLOUR,
  DEFAULT_HANDLE_BORDER_COLOUR,
  DEFAULT_HANDLE_FILL_COLOUR,
  DEFAULT_MARKUP_SELECTION_FILL,
  DEFAULT_MARKUP_SELECTION_STROKE,
  DEFAULT_STROKE_PREVIEW_COLOUR,
  HALF_HANDLE_VISUAL,
  HANDLE_HIT_PADDING,
  HANDLE_HIT_SIZE,
  HANDLE_VISUAL_SIZE,
  type HandlePosition,
  LINE_INTERACTION_PADDING,
  type LineHandlePosition,
  MIN_RESIZE_SIZE,
  MOUSE_DRAG_POINTER_ID,
  RECT_EPSILON,
} from './selection-overlay-constants.js';
export type {
  BoxDragSession,
  BoxMoveDragSession,
  BoxResizeDragSession,
  DragSession,
  LineDragSession,
  LineMoveDragSession,
  LineResizeDragSession,
} from './selection-overlay-drag-session.types.js';
